### ISSUE TITLE
demo error

### ISSUE THREAD

**Issue by liuao743** [IDEA-Research/MotionLLM#4]
When I use the online demo:
![938fd5e96696335224c7e13351a8fc2](https://github.com/IDEA-Research/MotionLLM/assets/62134958/98176eb3-b919-4c96-8ffa-36703c5ab5a6)

**Comment by LinghaoChan** [comment]
> When I use the online demo: ![938fd5e96696335224c7e13351a8fc2](https://private-user-images.githubusercontent.com/62134958/336765674-98176eb3-b919-4c96-8ffa-36703c5ab5a6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc1ODQ5MjQsIm5iZiI6MTcxNzU4NDYyNCwicGF0aCI6Ii82MjEzNDk1OC8zMzY3NjU2NzQtOTgxNzZlYjMtYjkxOS00Yzk2LThmZmEtMzY3MDNjNWFiNWE2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjA1VDEwNTAyNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTEwY2JiNWFmNTlhMTY5NGFlYTZmY2ZhMTJiODljZmRhMGE4M2IyM2I0YmU3M2Y3ODA0YTkyZWUzMjZkODA3MTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.jaqI-iy66PNlTGj72oghtnWUBW5qbdx42ueZHOvslMM)

Could you please refresh the page and have a try?

**Comment by LinghaoChan** [comment]
PS: you can also check your terminal output.

**Comment by LinghaoChan** [comment]
@liuao743 has your issue been resolved?

**Comment by liuao743** [comment]
> @liuao743 has your issue been resolved?

No, also, when I run the demo locally, it gives me :
![1742def1fa8d7b43e46c48feabae56d](https://github.com/IDEA-Research/MotionLLM/assets/62134958/fb4c1bb0-9abb-403d-ae67-df4362558736)

**Comment by JiaweiMorris** [comment]
在线demo出现了同样的问题，是上传文件的格式问题吗？尝试了.avi和.mp4都是相同的报错，尝试左下角的example可以正常输出

**Comment by LinghaoChan** [comment]
> > @liuao743 has your issue been resolved?
> 
> No, also, when I run the demo locally, it gives me : ![1742def1fa8d7b43e46c48feabae56d](https://private-user-images.githubusercontent.com/62134958/337620212-fb4c1bb0-9abb-403d-ae67-df4362558736.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc4MjAwNzUsIm5iZiI6MTcxNzgxOTc3NSwicGF0aCI6Ii82MjEzNDk1OC8zMzc2MjAyMTItZmI0YzFiYjAtOWFiYi00MDNkLWFlNjctZGY0MzYyNTU4NzM2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjA4VDA0MDkzNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVjZmI2YmQwMzA0ZWI0NmVhMjQyZWQ2NWMyM2RlMzJhYTYyMzFjNjMzMjc5ZWI4YTFhYmE3YmU2YjRkM2EwOWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.5I2Tid1F8a1L4dYFPxfg1oeHKWdSg-HLf0FJLToc-cE)

@liuao743 Have you downloaded the vicuna 1.5 properly?

**Comment by LinghaoChan** [comment]
> > > @liuao743 has your issue been resolved?
> > 
> > 
> > No, also, when I run the demo locally, it gives me : ![1742def1fa8d7b43e46c48feabae56d](https://private-user-images.githubusercontent.com/62134958/337620212-fb4c1bb0-9abb-403d-ae67-df4362558736.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc4MjAwNzUsIm5iZiI6MTcxNzgxOTc3NSwicGF0aCI6Ii82MjEzNDk1OC8zMzc2MjAyMTItZmI0YzFiYjAtOWFiYi00MDNkLWFlNjctZGY0MzYyNTU4NzM2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjA4VDA0MDkzNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVjZmI2YmQwMzA0ZWI0NmVhMjQyZWQ2NWMyM2RlMzJhYTYyMzFjNjMzMjc5ZWI4YTFhYmE3YmU2YjRkM2EwOWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.5I2Tid1F8a1L4dYFPxfg1oeHKWdSg-HLf0FJLToc-cE)
> 
> @liuao743 Have you downloaded the vicuna 1.5 properly?

@liuao743 Please paste your full traceback

**Comment by LinghaoChan** [comment]
> 在线demo出现了同样的问题，是上传文件的格式问题吗？尝试了.avi和.mp4都是相同的报错，尝试左下角的example可以正常输出

yes, exactly. Please check the file format or upgrade the version of gradio/browser.

**Comment by LinghaoChan** [comment]
@liuao743 @JiaweiMorris Have you resolved the issue? We can actively align the details of your bugs.

**Comment by JiaweiMorris** [comment]
> @liuao743 @JiaweiMorris Have you resolved the issue? We can actively align the details of your bugs.

没有，您可以提供不是直接点击网页左下角而是能够上传并成功获得回答的视频样例吗？

**Comment by LinghaoChan** [comment]
> > @liuao743 @JiaweiMorris Have you resolved the issue? We can actively align the details of your bugs.
> 
> 没有，您可以提供不是直接点击网页左下角而是能够上传并成功获得回答的视频样例吗？

@JiaweiMorris Some peers pinged me that they have run the codes successfully. Could you please check following questions? 

1. You can check the log. What is the full error message?
2. You can upload the video I provide as examples. 
3. What is your gradio version?
4. You can choose the CLI mode we uploaded 2 days before.

**Comment by JiaweiMorris** [comment]
刚刚测试在线demo可以上传mp4和avi了，请问什么时候可以上传motion文件呢？以及它们的格式要求是什么呢？

**Comment by LinghaoChan** [comment]
> 刚刚测试在线demo可以上传mp4和avi了，请问什么时候可以上传motion文件呢？以及它们的格式要求是什么呢？

@JiaweiMorris We are now thinking about how to support the motion data. This might not be our current highest priority. To our observation, the dataset is in the largest demand to the community now, which in at the highest priority.

**Comment by LinghaoChan** [comment]
Seems there is no further issue on the demo bug. I provide more info about deploying the demo on [HF](https://huggingface.co/spaces/EvanTHU/MotionLLM/tree/main).
