### ISSUE TITLE
Multi-round chat

### ISSUE THREAD

**Issue by SeanChenxy** [IDEA-Research/MotionLLM#5]
Hi, thanks for providing codes of #2. Could the model supports Multi-round chat based on #2?

**Comment by LinghaoChan** [comment]
> Hi, thanks for providing codes of #2. Could the model supports Multi-round chat based on #2?

@SeanChenxy Multi-round chat is available. But now, we do not have enough time to support this function in this demo version. The dataset and huggingface demo are at a higher priority. You can achieve multi-round chat via concat operation.

**Comment by SeanChenxy** [comment]
ic. Thanks a lot.
