### ISSUE TITLE
Has anyone successfully run this project?

### ISSUE THREAD

**Issue by LinaZhangCoding** [IDEA-Research/MotionLLM#6]
<img width="453" alt="截屏2024-06-27 15 49 47" src="https://github.com/IDEA-Research/MotionLLM/assets/170146562/aa21f46d-8dad-4049-b0f2-d44d1749a294">

When pip install -r requirements.txt, many bugs are reported，such as shown in the image. After solving this, it shows other errors like packaging, deepspeed, flash_attn.

**Comment by LinghaoChan** [comment]
I think [this commit](https://github.com/IDEA-Research/MotionLLM/commit/1e85527ea3146f6ad6f0df2bea97e783330cf57d) has resolved your issue.
