### ISSUE TITLE
Details of the evaluation protocol of MoVid-Bench.

### ISSUE THREAD

**Issue by yxsysu** [IDEA-Research/MotionLLM#8]
Hi, author.
Thanks for your great work. After downloading the dataset from the huggingface, we found video-QA.json and all.txt in the folder. The annotations are detailed. But we are wondering about the dataset split of training and testing, and how to obtain the results in Table 4. 
![image](https://github.com/user-attachments/assets/79845f1f-30bf-4b52-b4f5-cb6d4820337a)

Thank you for your reply.

**Comment by LinghaoChan** [comment]
@yxsysu Hi! Thanks for your interest. The MoVid benchmark is not publicly available yet. We plan to release it in recent weeks. The benchmark is not the dataset. Our benchmark includes more complex QAs. Besides, our released data is just caption, which does not include complex QAs. The complex QAs are expected to be released in this month or early Sepetember.
