### ISSUE TITLE
Guideline for generating correct lit_model.pth

### ISSUE THREAD

**Issue by mkeya013** [IDEA-Research/MotionLLM#9]
Dear Author, is it possible to provide correct lit_model.pth file? Or a guideline to generate correct lit_model.pth file would be a great help. 

Thank you.

**Comment by LinghaoChan** [comment]
@mkeya013 Thanks for your question. 

1. git clone the `lit-gpt' and go into the corresponding dictionary.
```
git clone https://github.com/Lightning-AI/litgpt.git
cd litgpt
git checkout d78730a0694bff6c9f1ce285a6e8b471c1321cf5
cd ./litgpt/scripts
```
To see all the available checkpoints for Vicuna, run:

```bash
python scripts/download.py | grep vicuna
```

which will print

```text
lmsys/vicuna-7b-v1.3
lmsys/vicuna-13b-v1.3
lmsys/vicuna-33b-v1.3
lmsys/vicuna-7b-v1.5
lmsys/vicuna-7b-v1.5-16k
lmsys/vicuna-13b-v1.5
lmsys/vicuna-13b-v1.5-16k
```

2. Download the model. 

In order to use a specific Vicuna checkpoint, for instance [vicuna-7b-v1.5](https://huggingface.co/lmsys/vicuna-7b-v1.5), download the weights and convert the checkpoint to the lit-gpt format:

```bash
pip install huggingface_hub

python scripts/download.py --repo_id lmsys/vicuna-7b-v1.5

python scripts/convert_hf_checkpoint.py --checkpoint_dir checkpoints/lmsys/vicuna-7b-v1.5
```

By default, the convert_hf_checkpoint step will use the data type of the HF checkpoint's parameters. In cases where RAM
or disk size is constrained, it might be useful to pass `--dtype bfloat16` to convert all parameters into this smaller precision before continuing.

You're done! To execute the model just run:

```bash
pip install sentencepiece

python chat/base.py --checkpoint_dir checkpoints/lmsys/vicuna-7b-v1.5
```

---

This is the vicuna version I used. You can also follow the latest [official guideline](https://github.com/Lightning-AI/litgpt?tab=readme-ov-file#finetune-an-llm) and revise it to vicuna-7b-1.5.

**Comment by mkeya013** [comment]
It worked. Thank you.

**Comment by CMY-CTO** [comment]
Dear Author,

For **Step1: git clone the `lit-gpt' and go into the corresponding dictionary.**

It's not workin
![image](https://github.com/user-attachments/assets/57d09af0-998f-422f-996d-14c77f3e7287)

Is it possible to provide correct repository？

Thank you.

**Comment by LinghaoChan** [comment]
@CMY-CTO sry for this. plz revise as

```
git clone https://github.com/Lightning-AI/litgpt.git
cd litgpt
git checkout d78730a0694bff6c9f1ce285a6e8b471c1321cf5
```

**Comment by LinghaoChan** [comment]
> @LinghaoChan 你好，我按照这个流程操作的时候报错 from litgpt.scripts.convert_hf_checkpoint import convert_hf_checkpoint ModuleNotFoundError: No module named 'litgpt' 请问该怎么修改啊，从huggingface或是modelscope的模型库中好像都有没有lit_model.pth这个模型

@ransheng11 需要按照README所说下载vicuna-1.5-7B的model哦～～～

**Comment by ransheng11** [comment]
> > @LinghaoChan 你好，我按照这个流程操作的时候报错 from litgpt.scripts.convert_hf_checkpoint import convert_hf_checkpoint ModuleNotFoundError: No module named 'litgpt' 请问该怎么修改啊，从huggingface或是modelscope的模型库中好像都有没有lit_model.pth这个模型
> 
> @ransheng11 需要按照README所说下载vicuna-1.5-7B的model哦～～～

<img width="522" alt="image" src="https://github.com/user-attachments/assets/2f0247c8-82e2-4f79-863f-90d4b9fc356a" />

你好，谢谢你的及时回答，我的问题可能有点白痴了，我现在仍然没有运行成功
1.python scripts/download.py --repo_id lmsys/vicuna-7b-v1.5
2.python scripts/convert_hf_checkpoint.py --checkpoint_dir checkpoints/lmsys/vicuna-7b-v1.5
在运行第一个命令的时候报如下错误，我用其他方式下载了模型如图
raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: (ProtocolError('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer')), '(Request ID: c301ebb9-2ae9-44b6-8071-74d95a5a9ad4)')
运行第二个命令的时候报如下错误，但我在huggingface和modelscope都没有看到有这个文件
FileNotFoundError: [Errno 2] No such file or directory: 'checkpoints/lmsys/vicuna-7b-v1.5/model_config.yaml'

**Comment by LinghaoChan** [comment]
> > > @LinghaoChan 你好，我按照这个流程操作的时候报错 from litgpt.scripts.convert_hf_checkpoint import convert_hf_checkpoint ModuleNotFoundError: No module named 'litgpt' 请问该怎么修改啊，从huggingface或是modelscope的模型库中好像都有没有lit_model.pth这个模型
> > 
> > 
> > @ransheng11 需要按照README所说下载vicuna-1.5-7B的model哦～～～
> 
> <img alt="image" width="522" src="https://private-user-images.githubusercontent.com/74763941/396051401-2f0247c8-82e2-4f79-863f-90d4b9fc356a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQzNTE0MjgsIm5iZiI6MTczNDM1MTEyOCwicGF0aCI6Ii83NDc2Mzk0MS8zOTYwNTE0MDEtMmYwMjQ3YzgtODJlMi00Zjc5LTg2M2YtOTBkNGI5ZmMzNTZhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjE2VDEyMTIwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ4OGM1YjM3ZDU3YWQxZGYzOTRmMTdjYTBjNDE1OWVkYjRjOWNlM2M0ZjE2ZTYwOTkzZGMyODg0ODlkNmNjZDcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.uHKHjCMNpTeHT9_ifmaSzBldBeSVEEskzaIEE5ho5xo">
> 你好，谢谢你的及时回答，我的问题可能有点白痴了，我现在仍然没有运行成功 1.python scripts/download.py --repo_id lmsys/vicuna-7b-v1.5 2.python scripts/convert_hf_checkpoint.py --checkpoint_dir checkpoints/lmsys/vicuna-7b-v1.5 在运行第一个命令的时候报如下错误，我用其他方式下载了模型如图 raise ConnectionError(err, request=request) requests.exceptions.ConnectionError: (ProtocolError('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer')), '(Request ID: c301ebb9-2ae9-44b6-8071-74d95a5a9ad4)') 运行第二个命令的时候报如下错误，但我在huggingface和modelscope都没有看到有这个文件 FileNotFoundError: [Errno 2] No such file or directory: 'checkpoints/lmsys/vicuna-7b-v1.5/model_config.yaml'

Please refer to the guidance provided by lig-gpt.

**Comment by ransheng11** [comment]
@LinghaoChan Thanks. I think I have followed the guidelines of litgpt. But it's okay. I have downloaded the model from hf. But now I get an out-of-memory error when running cli. I have 24GB of memory. Does motionllm support multiple cards? And does it support fine-tuning with custom datasets?

**Comment by JackYu6** [comment]
After running
```
python scripts/download.py --repo_id lmsys/vicuna-7b-v1.5
```
I encountered the following error:
```
Traceback (most recent call last):
  File "/home/user/miniconda3/lib/python3.11/site-packages/litgpt/config.py", line 121, in from_name
    conf_dict = next(
                ^^^^^
StopIteration

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/user/litgpt/litgpt/scripts/download.py", line 137, in <module>
    CLI(download_from_hub)
  File "/home/user/miniconda3/lib/python3.11/site-packages/litgpt/utils.py", line 466, in CLI
    return CLI(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/user/miniconda3/lib/python3.11/site-packages/jsonargparse/_cli.py", line 96, in CLI
    return _run_component(components, init)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/miniconda3/lib/python3.11/site-packages/jsonargparse/_cli.py", line 204, in _run_component
    return component(**cfg)
           ^^^^^^^^^^^^^^^^
  File "/home/user/litgpt/litgpt/scripts/download.py", line 107, in download_from_hub
    convert_hf_checkpoint(checkpoint_dir=directory, dtype=dtype, model_name=model_name)
  File "/home/user/miniconda3/lib/python3.11/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/miniconda3/lib/python3.11/site-packages/litgpt/scripts/convert_hf_checkpoint.py", line 524, in convert_hf_checkpoint
    config = Config.from_name(model_name)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/miniconda3/lib/python3.11/site-packages/litgpt/config.py", line 128, in from_name
    raise ValueError(f"{name!r} is not a supported config name")
ValueError: 'vicuna-7b-v1.5' is not a supported config name
```
How can I fix it? Thx.

**Comment by conc1se333** [comment]
> After running
> 
> ```
> python scripts/download.py --repo_id lmsys/vicuna-7b-v1.5
> ```
> 
> I encountered the following error:
> 
> ```
> Traceback (most recent call last):
>   File "/home/user/miniconda3/lib/python3.11/site-packages/litgpt/config.py", line 121, in from_name
>     conf_dict = next(
>                 ^^^^^
> StopIteration
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/home/user/litgpt/litgpt/scripts/download.py", line 137, in <module>
>     CLI(download_from_hub)
>   File "/home/user/miniconda3/lib/python3.11/site-packages/litgpt/utils.py", line 466, in CLI
>     return CLI(*args, **kwargs)
>            ^^^^^^^^^^^^^^^^^^^^
>   File "/home/user/miniconda3/lib/python3.11/site-packages/jsonargparse/_cli.py", line 96, in CLI
>     return _run_component(components, init)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/home/user/miniconda3/lib/python3.11/site-packages/jsonargparse/_cli.py", line 204, in _run_component
>     return component(**cfg)
>            ^^^^^^^^^^^^^^^^
>   File "/home/user/litgpt/litgpt/scripts/download.py", line 107, in download_from_hub
>     convert_hf_checkpoint(checkpoint_dir=directory, dtype=dtype, model_name=model_name)
>   File "/home/user/miniconda3/lib/python3.11/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
>     return func(*args, **kwargs)
>            ^^^^^^^^^^^^^^^^^^^^^
>   File "/home/user/miniconda3/lib/python3.11/site-packages/litgpt/scripts/convert_hf_checkpoint.py", line 524, in convert_hf_checkpoint
>     config = Config.from_name(model_name)
>              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/home/user/miniconda3/lib/python3.11/site-packages/litgpt/config.py", line 128, in from_name
>     raise ValueError(f"{name!r} is not a supported config name")
> ValueError: 'vicuna-7b-v1.5' is not a supported config name
> ```
> 
> How can I fix it? Thx.

I ran into the same issue. Did you solve it?

**Comment by cjwku1209** [comment]
You might have downloaded the `litgpt` package and are not running the `config.py` script locally. To resolve this issue, you can use the `-m` flag to ensure that Python runs the script as a module and can correctly locate `litgpt`.

```bash
pip uninstall litgpt
python -m litgpt.scripts.download --repo_id lmsys/vicuna-7b-v1.5
python scripts/convert_hf_checkpoint.py --checkpoint_dir checkpoints/lmsys/vicuna-7b-v1.5
```

This should ensure the correct setup and allow the script to locate the necessary files.

**Comment by svical** [comment]
> > After running
> > ```
> > python scripts/download.py --repo_id lmsys/vicuna-7b-v1.5
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > I encountered the following error:
> > ```
> > Traceback (most recent call last):
> >   File "/home/user/miniconda3/lib/python3.11/site-packages/litgpt/config.py", line 121, in from_name
> >     conf_dict = next(
> >                 ^^^^^
> > StopIteration
> > 
> > During handling of the above exception, another exception occurred:
> > 
> > Traceback (most recent call last):
> >   File "/home/user/litgpt/litgpt/scripts/download.py", line 137, in <module>
> >     CLI(download_from_hub)
> >   File "/home/user/miniconda3/lib/python3.11/site-packages/litgpt/utils.py", line 466, in CLI
> >     return CLI(*args, **kwargs)
> >            ^^^^^^^^^^^^^^^^^^^^
> >   File "/home/user/miniconda3/lib/python3.11/site-packages/jsonargparse/_cli.py", line 96, in CLI
> >     return _run_component(components, init)
> >            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> >   File "/home/user/miniconda3/lib/python3.11/site-packages/jsonargparse/_cli.py", line 204, in _run_component
> >     return component(**cfg)
> >            ^^^^^^^^^^^^^^^^
> >   File "/home/user/litgpt/litgpt/scripts/download.py", line 107, in download_from_hub
> >     convert_hf_checkpoint(checkpoint_dir=directory, dtype=dtype, model_name=model_name)
> >   File "/home/user/miniconda3/lib/python3.11/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
> >     return func(*args, **kwargs)
> >            ^^^^^^^^^^^^^^^^^^^^^
> >   File "/home/user/miniconda3/lib/python3.11/site-packages/litgpt/scripts/convert_hf_checkpoint.py", line 524, in convert_hf_checkpoint
> >     config = Config.from_name(model_name)
> >              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> >   File "/home/user/miniconda3/lib/python3.11/site-packages/litgpt/config.py", line 128, in from_name
> >     raise ValueError(f"{name!r} is not a supported config name")
> > ValueError: 'vicuna-7b-v1.5' is not a supported config name
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > How can I fix it? Thx.
> 
> I ran into the same issue. Did you solve it?

I checked the litgpt repo readme that Vicuna is not supported now. But it was supported in Sep 2024. So make sure you use the right branch.
```
git checkout d78730a0694bff6c9f1ce285a6e8b471c1321cf5
```

**Comment by yuafowo** [comment]
> [@LinghaoChan](https://github.com/LinghaoChan) Thanks. I think I have followed the guidelines of litgpt. But it's okay. I have downloaded the model from hf. But now I get an out-of-memory error when running cli. I have 24GB of memory. Does motionllm support multiple cards? And does it support fine-tuning with custom datasets?

Bro, have you solved this problem? I also encountered OOM issues.
